### PR TITLE
Add documentation for Ch 6 and Tidyverse review

### PR DESCRIPTION
**Pull request by villegar**

### CODE REVIEW

**Review by jonthegeek — CHANGES_REQUESTED** [review]
Hmm. It says I have to use the command line to resolve conflicts. Any idea what's wrong?

**Review by villegar — COMMENTED** [review]
I have manually inspected the changes, most differences are because I traduced the contents in Chapter 6. So, I think pulling the changes from my repo is safe.

**Comment by jonthegeek** [comment]
> I have manually inspected the changes, most differences are because I traduced the contents in Chapter 6. So, I think pulling the changes from my repo is safe.

The branch has merge conflicts. It *can't* be merged until they're resolved. Normally I can do this, but I can't here, so I think that means you didn't allow changes from the repo maintainers. Be sure to check that box in the future when you crest the pr.

In the web interface here, deal with the grey stuff near the bottom.

**Comment by jonthegeek** [comment]
I ran:

```
usethis::pr_fetch(3) # Get this PR to my machine.
usethis::pr_merge_main() # Merge the main branch back in.
```

That resulted in warnings about 3 merge conflicts:

```
Merge has resulted in merge conflict(s).
There are 3 conflicted files:
* '03-extra-tidyverse-review.Rmd'
* '06-fitting_models_with_parsnip.Rmd'
* 'README.md'
Are you ready to sort this out?
If so, we will open the conflicted files for you to edit.

1: Yes, I'm ready to resolve the merge conflicts.
2: No, I want to abort this merge.

Selection: 1
```

It intentionally errors at this point, but opens the files for editing:

```
Error: Please fix each conflict, save, stage, and commit.
To back out of this merge, run `gert::git_merge_abort()` (in R) or `git merge --abort` (in the shell).
```

I then manually edited, watching out for things like this:

```
<<<<<<< HEAD
  <summary> Chat de la Reunión </summary>
=======
  <summary> Chat de la reunión </summary>
>>>>>>> 45448e0332e39ea47878c8f55cd24d02fb9892d1
```

Normally github lets me do this through a web interface, I'm not sure why I had to use usethis to fix this... but I think it's fixed!

**Review by jonthegeek — DISMISSED** [review]
When/if the build passes, these changes are great!

**Comment by jonthegeek** [comment]
Working on fixing the build. It looks like at least one function moved from {discrim} to {parsnip}, I'm doing a full build locally to make sure nothing else breaks. Update: {baguette} had a similar function move to {parsnip}.

**Review by jonthegeek — APPROVED** [review]
Ok, I think that fixed everything!

**Pull request merged**
